#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

grep -v '^#!' $1 | cpp > $1.full &&
node "$DIR"/preprocess.js $1.full &&
glslangValidator -V -o $2 $1.full.comp | grep -v "^$1.full.comp$"
cat $1.full.defs.spv >> $2
# && rm $1.full $1.full.comp $1.full.defs.spv
